[project]
name = "sensors"
version = "0.1.0"
description = "Simulating iot-parking sensors behavior through MQTT."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "paho-mqtt>=2.1.0",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
]
